# Generated by Django 3.0.14 on 2023-11-24 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreriaApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='sinopsis',
        ),
    ]
