# Generated by Django 3.0.14 on 2023-11-30 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libreriaApp', '0002_remove_libro_sinopsis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='fecha_nacimiento',
            new_name='fechaNaci',
        ),
        migrations.RenameField(
            model_name='libro',
            old_name='fecha_publicacion',
            new_name='fechaPubli',
        ),
        migrations.AlterField(
            model_name='libro',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreriaApp.autor'),
        ),
    ]
