# Generated by Django 3.0.14 on 2023-12-22 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libreriaApp', '0014_auto_20231222_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreriaApp.autor'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
